name: 'Setup GitHub Container Registry'
description: 'Determine the URL and authenticate'

inputs:
  image-name:
    description: >
      Image name.
      Leave empty to use repository name.
    required: false
    default: ''
  github-token:
    description: >
      GitHub Token with permissions to write to GitHub Container Registry.
    required: true

outputs:
  registry:
    description: >
      Registry URL
    value: ${{ steps.setup.outputs.registry }}
  image-name:
    description: >
      Image name
    value: ${{ steps.setup.outputs.image-name }}
  url:
    description: >
      Full URL (registry + image name)
    value: ${{ steps.setup.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: 'Determine registry URL'
      id: setup
      shell: bash
      run: |
        registry="ghcr.io/${{ github.repository_owner }}"
        echo "registry=$registry" | tee -a "$GITHUB_OUTPUT"

        image_name="${{ inputs.image-name }}"
        if [ -z "$image_name" ]
        then
          image_name="${{ github.event.repository.name }}"
        fi
        echo "image-name=$image_name" | tee -a "$GITHUB_OUTPUT"

        echo "url=${registry}/$image_name" | tee -a "$GITHUB_OUTPUT"

    - name: 'Authenticate'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}
