name: Setup
description: Setup Node.js and install dependencies

inputs:
  fetch-depth:
    description: 'Git fetch depth passed to actions/checkout. Pass 0 to fetch full history.'
    required: false
    default: '1'
  working-directory:
    description: 'Directory in which to run things in.'
    required: false
    default: '.'

outputs:
  scripts:
    description: "Comma–separated list of available npm scripts. Includes comma at the beginning and the end, so you can use contains(needs.setup.outputs.scripts, ',script-name,')"
    value: ${{ steps.scripts.outputs.scripts }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ github.event.pull_request.head.ref || github.ref }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '${{ inputs.working-directory }}/.nvmrc'

    - name: Collect npm scripts
      id: scripts
      working-directory: ${{ inputs.working-directory }}
      shell: sh
      run: |
        npm_scripts="$(
          jq -r '.scripts | keys | .[]' package.json | paste -sd,
        )"
        echo "Detected npm scripts: $npm_scripts"
        echo "scripts=,$npm_scripts," >> "$GITHUB_OUTPUT"

    - name: Calculate cache key parts
      id: cache-keys
      uses: verkstedt/actions/cache-keys@v1
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Restore cache
      id: cache
      uses: actions/cache/restore@v4
      # ⚠ Keep in sync with cache/save below
      with:
        path: |
          ${{ inputs.working-directory }}/node_modules/
          ${{ inputs.working-directory }}/.yarn/install-state.gz
        key: |
          npm--${{ steps.cache-keys.outputs.os }}--${{ steps.cache-keys.outputs.node }}--${{ steps.cache-keys.outputs.packageJson }}--${{ steps.cache-keys.outputs.packageJsonLock }}
        restore-keys: |
          npm--${{ steps.cache-keys.outputs.os }}--${{ steps.cache-keys.outputs.node }}--${{ steps.cache-keys.outputs.packageJson }}--
          npm--${{ steps.cache-keys.outputs.os }}--${{ steps.cache-keys.outputs.node }}--

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        if [ -e "yarn.lock" ]
        then
          yarn install --immutable
        else
          npm ci
        fi

    - name: Save cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      # ⚠ Keep in sync with cache/restore above
      with:
        path: |
          ${{ inputs.working-directory }}/node_modules/
          ${{ inputs.working-directory }}/.yarn/install-state.gz
        key: |
          npm--${{ steps.cache-keys.outputs.os }}--${{ steps.cache-keys.outputs.node }}--${{ steps.cache-keys.outputs.packageJson }}--${{ steps.cache-keys.outputs.packageJsonLock }}
