name: 'Chromatic'

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory in which to run things in.'
        type: string
        required: false
        default: '.'

jobs:
  chromatic:
    name: 'Chromatic'
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'storybook' || 'PR storybook' }}
      url: ${{ steps.publish.outputs.storybookUrl == 'undefined' && '' || steps.publish.outputs.storybookUrl }}
    steps:
      - name: Verify workflow setup
        run: |
          exit_code=0

          if [ -z "${{ secrets.CHROMATIC_PROJECT_TOKEN }}" ]
          then
            echo "::error::Missing secret CHROMATIC_PROJECT_TOKEN. You can get it https://www.chromatic.com/start, then open your project and go to “Manage” → “Configure”."
            exit_code=78
          fi

          exit $exit_code

      - name: Setup
        uses: verkstedt/actions/setup@main
        with:
          working-directory: ${{ inputs.working-directory }}
          fetch-depth: 0

      - name: Build StoryBook
        working-directory: ${{ inputs.working-directory }}
        run: |
          npx storybook build --webpack-stats-json

      - name: Publish to Chromatic
        id: publish
        uses: chromaui/action@latest
        with:
          workingDir: ${{ inputs.working-directory }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Take screenshots only of components that changed
          onlyChanged: true
          # We assume that everything that goes to main has already been
          # approved on the PR level
          autoAcceptChanges: main
          # Use StoryBook build from previous step
          storybookBuildDir: ./storybook-static/
          # Don’t want for the build to finish before continuing.
          # This require Chromatic is connected to GitHub repo and will
          # report it’s own checks, which we can use as required for
          # merging branches.
          exitOnceUploaded: true
