name: 'CI'

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Directory in which to run things in.'
        type: string
        required: false
        default: '.'
    secrets:
      build_env:
        description: 'Environment variables to set when running build script.'
        required: false

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  # Each job here will use verkstedt/action/setup which checks out the
  # code and runs `npm install`, caching the results.
  # We run this job with just `setup` before anything else to make sure
  # that cache is filled up for all other jobs.
  initial-setup:
    name: 'Initial setup'
    runs-on: ubuntu-latest
    if: github.head_ref == 'main' || github.event.pull_request.draft == false
    outputs:
      scripts: ${{ steps.setup.outputs.scripts }}
    steps:
      - name: Setup
        id: setup
        uses: verkstedt/actions/setup@v1
        with:
          working-directory: ${{ inputs.working-directory }}

  lint-js:
    name: 'Lint JS'
    runs-on: ubuntu-latest
    if: contains(needs.initial-setup.outputs.scripts, ',lint:js,')
    needs:
      - initial-setup
    steps:
      - name: Setup
        uses: verkstedt/actions/setup@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      # Once https://github.com/actions/setup-node/issues/96 is
      # implemented, next two steps can be replaced with just:
      #
      # - name: Lint JS
      #   run: npm lint:js

      - name: Lint JS
        id: lint
        working-directory: ${{ inputs.working-directory }}
        run: |
          if jq -r '.scripts["lint:js"]' package.json | grep -qE '^(eslint|next lint) '
          then
            npm run lint:js -- --format=json --output-file=eslint_report.json || :
            echo 'generated-eslint-report=true' >> "$GITHUB_OUTPUT"
          else
            npm run lint:js
            echo 'generated-eslint-report=false' >> "$GITHUB_OUTPUT"
          fi

      - name: Annotate
        if: steps.lint.outputs.generated-eslint-report == 'true'
        uses: ataylorme/eslint-annotate-action@v3
        with:
          report-json: eslint_report.json
          # Also report errors in files not changed in the PR,
          # assuring there are no errors in the whole codebase
          only-pr-files: false

  lint-ts:
    name: 'Lint TS'
    runs-on: ubuntu-latest
    if: contains(needs.initial-setup.outputs.scripts, ',lint:ts,')
    needs:
      - initial-setup
    steps:
      - name: Setup
        uses: verkstedt/actions/setup@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Lint TS
        working-directory: ${{ inputs.working-directory }}
        run: npm run lint:ts

  lint-css:
    name: 'Lint CSS'
    runs-on: ubuntu-latest
    if: contains(needs.initial-setup.outputs.scripts, ',lint:css,')
    needs:
      - initial-setup
    steps:
      - name: Setup
        uses: verkstedt/actions/setup@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Lint CSS
        working-directory: ${{ inputs.working-directory }}
        run: |
          npm run lint:css

  lint-missing-translations:
    name: 'Lint missing translations'
    runs-on: ubuntu-latest
    if: contains(needs.initial-setup.outputs.scripts, ',lint:missing-translations,')
    needs:
      - initial-setup
    steps:
      - name: Setup
        uses: verkstedt/actions/setup@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Lint Translations
        working-directory: ${{ inputs.working-directory }}
        run: npm run lint:missing-translations

  # We prefer to have lint script split into lint:*, but will use
  # generic lint if no lint:* scripts are found
  lint-fallback:
    name: 'Lint fallback'
    runs-on: ubuntu-latest
    if: >
      contains(needs.initial-setup.outputs.scripts, ',lint,')
      && ! contains(needs.initial-setup.outputs.scripts, ',lint:')
    needs:
      - initial-setup
    steps:
      - name: Setup
        uses: verkstedt/actions/setup@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Lint fallback
        working-directory: ${{ inputs.working-directory }}
        run: npm run lint

  test-unit:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    if: >
      '# Don’t skip if any of the needs (apart from initial-setup) are skipped'
      && !cancelled()
      && needs.initial-setup.result != 'skipped'
      && ! contains(needs.*.result, 'failure')
      && contains(needs.initial-setup.outputs.scripts, ',test:unit,')
    needs:
      - initial-setup
      - lint-js
      - lint-ts
      - lint-fallback
    steps:
      - name: Setup
        uses: verkstedt/actions/setup@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Test units
        working-directory: ${{ inputs.working-directory }}
        run: npm run test:unit

  test-end-to-end:
    name: 'End to end tests'
    runs-on: ubuntu-latest
    if: >
      '# Don’t skip if any of the needs (apart from initial-setup) are skipped'
      && !cancelled()
      && needs.initial-setup.result != 'skipped'
      && ! contains(needs.*.result, 'failure')
      && contains(needs.initial-setup.outputs.scripts, ',test:end-to-end,')
    needs:
      - initial-setup
      - lint-js
      - lint-ts
      - lint-fallback
    steps:
      - name: Setup
        uses: verkstedt/actions/setup@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Test units
        working-directory: ${{ inputs.working-directory }}
        run: npm run test:end-to-end

  # We prefer to have test script split into test:*, but will use
  # generic test if no test:* scripts are found
  test-fallback:
    name: 'Test fallback'
    runs-on: ubuntu-latest
    if: >
      '# Don’t skip if any of the needs (apart from initial-setup) are skipped'
      && !cancelled()
      && needs.initial-setup.result != 'skipped'
      && ! contains(needs.*.result, 'failure')
      && contains(needs.initial-setup.outputs.scripts, ',test,')
      && ! contains(needs.initial-setup.outputs.scripts, ',test:')
    needs:
      - initial-setup
      - lint-js
      - lint-ts
      - lint-fallback
    steps:
      - name: Setup
        uses: verkstedt/actions/setup@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Test fallback
        working-directory: ${{ inputs.working-directory }}
        run: npm run test

  build:
    name: 'Build'
    runs-on: ubuntu-latest
    if: >
      '# Don’t skip if any of the needs (apart from initial-setup) are skipped'
      && !cancelled()
      && needs.initial-setup.result != 'skipped'
      && ! contains(needs.*.result, 'failure')
      && contains(needs.initial-setup.outputs.scripts, ',build,')
    needs:
      - initial-setup
      # all linters:
      - lint-js
      - lint-ts
      - lint-css
      - lint-missing-translations
      - lint-fallback
      # all testers:
      - test-unit
      - test-fallback
    steps:
      - name: Setup
        uses: verkstedt/actions/setup@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Set environment variables
        working-directory: ${{ inputs.working-directory }}
        run: |
          echo "${{ secrets.build_env }}" >> "$GITHUB_ENV"

      - name: Calculate cache key parts
        id: cache-keys
        uses: verkstedt/actions/cache-keys@v1
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Restore cache
        id: cache
        uses: actions/cache/restore@v4
        # ⚠ Keep in sync with cache/save below
        with:
          path: |
            ${{ inputs.working-directory }}/.next/cache
          key: |
            build--${{ steps.cache-keys.outputs.os }}--${{ steps.cache-keys.outputs.node }}--${{ steps.cache-keys.outputs.packageJson }}--${{ steps.cache-keys.outputs.packageJsonLock }}--${{ steps.cache-keys.outputs.ref }}
          restore-keys: |
            build--${{ steps.cache-keys.outputs.os }}--${{ steps.cache-keys.outputs.node }}--${{ steps.cache-keys.outputs.packageJson }}--${{ steps.cache-keys.outputs.packageJsonLock }}--
            build--${{ steps.cache-keys.outputs.os }}--${{ steps.cache-keys.outputs.node }}--${{ steps.cache-keys.outputs.packageJson }}--
            build--${{ steps.cache-keys.outputs.os }}--${{ steps.cache-keys.outputs.node }}--
            build--${{ steps.cache-keys.outputs.os }}--

      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: npm run build

      - name: Save cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        # ⚠ Keep in sync with cache/restore above
        with:
          path: |
            ${{ inputs.working-directory }}/.next/cache
          key: |
            build--${{ steps.cache-keys.outputs.os }}--${{ steps.cache-keys.outputs.node }}--${{ steps.cache-keys.outputs.packageJson }}--${{ steps.cache-keys.outputs.packageJsonLock }}--${{ steps.cache-keys.outputs.ref }}

  check-licenses-compatibility:
    name: 'Check licenses compatibility'
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - initial-setup
    steps:
      - name: Setup
        uses: verkstedt/actions/setup@v1
        with:
          working-directory: ${{ inputs.working-directory }}
      - name: Check licenses compatibility
        id: check
        working-directory: ${{ inputs.working-directory }}
        env:
          ALLOWED_LICENSES: ${{ vars.ALLOWED_LICENSES }}
        run: |
          if [ -z "$ALLOWED_LICENSES" ]
          then
          echo '::error::Set ALLOWED_LICENSES GitHub actions variable with list of SPDX license identifiers (one per line, lines starting with # are comments). Tip: Do it on organisation level to avoid repeating it for each repository.'
            exit 64 # EX_USAGE
          fi

          this_package="$(
            node --no-warnings --input-type=module -e '
              import pkg from "./package.json" with { type: "json" };
              process.stdout.write(`${pkg.name}@${pkg.version}`);
            '
          )"
          licenses="$( echo "$ALLOWED_LICENSES" | grep -Ev '^\s*($|#)' | paste -sd';' )"

          exit_status_file=$( mktemp )
          output_file=$( mktemp )
          set +e
          {
            npx --yes --loglevel=error license-checker@25.0.1 \
              --production --onlyAllow="$licenses" --excludePackages "$this_package" \
              2>&1 1>/dev/null
            echo $? > "$exit_status_file"
          } | tee "$output_file"
          set -e

          {
            echo 'LINT_ERRORS_MARKDOWN<<EOM'
            sed \
              -e 's~ which is not permitted by the --onlyAllow flag\. Exiting\.$~.~' \
              -e 's~^~- ~g' \
              -e 's~"~`~g' \
              "$output_file"
            echo 'EOM'
          } >> "$GITHUB_ENV"

          exit $( cat "$exit_status_file" )
      - name: Notify about violations on PR
        uses: actions/github-script@v6
        if: failure() && github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Detected license issues in this PR:\n\n${process.env.LINT_ERRORS_MARKDOWN}\n`
            })
      - name: Notify about violations on main branch
        uses: slackapi/slack-github-action@v1
        if: failure() && github.head_ref == 'main'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: ${{ vars.LICENSE_VIOLATIONS_SLACK_CHANNEL_ID || vars.SLACK_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<!here> Detected license issues in <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}> @ ${{ github.head_ref || github.ref_name }}:\n\n${{ env.LINT_ERRORS_MARKDOWN }}\n"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Triggered by:"
                    },
                    {
                      "type": "image",
                      "alt_text": "",
                      "image_url": "${{ github.event.sender.avatar_url }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "<${{ github.event.sender.html_url }}|${{ github.event.sender.login }}>"
                    }
                  ]
                }
              ]
            }
