name: 'Reusable gcp cloud function deploy workflow'

on:
  workflow_call:
    inputs:
      function-name:
        required: true
        type: string
      region:
        required: true
        type: string
      source-dir:
        type: string
        default: "."
      entry-point:
        required: true
        type: string
      runtime:
        required: true
        type: string
      memory:
        type: string
        default: "256Mi"
      service-timeout:
        type: number
        default: 60
      workload-identity-provider:
        required: true
        type: string
      workload-identity-service-account-mail:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Google Auth
        uses: 'google-github-actions/auth@v3'
        with:
          service_account: ${{ inputs.workload-identity-service-account-mail }}
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
      - name: Set up gcloud-cli
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          version: '>= 363.0.0'
      - name: Deploy Cloud Function
        uses: google-github-actions/deploy-cloud-functions@v4
        with:
          name: ${{ inputs.function-name }}
          runtime: ${{ inputs.runtime }}
          region: ${{ inputs.region }}
          memory: ${{ inputs.memory }}
          service_timeout: ${{ inputs.service-timeout }}
          source_dir: ${{ inputs.source-dir }}
          entry_point: ${{ inputs.entry-point }}
