# Docker Build and Push
#
# Template to use with this workflow:
# https://github.com/verkstedt/.github/tree/main/workflow-templates/docker-build-push.yaml
#
# Build and push Docker images to multiple registries:
# - GitHub Container Registry (GHCR)
# - Amazon ECR (AWS Elastic Container Registry)
# - Google Artifact Registry
#
# Will tag all images with:
# - sha of the commit (`git-<short_sha>`)
#
# If version change is detected:
# - NO (meant for preview deployment)
#   - tag with `edge`
# - YES (meant for production deployment, unless it’s prerelease)
#   - tag with `v<new_version>`
#   - if version is not prerelease also with:
#     - `latest`
#     - `v<major>` and `v<major>.<minor>`

name: Docker Build and Push
on:
  workflow_call:
    secrets:
      BUILD_ARGS:
        description: 'Build arguments for Docker build (multiline string)'

    inputs:
      dry-run:
        description: 'Dry run mode (no pushing to registries)'
        type: boolean
        default: false

      # Build configuration
      context:
        description: 'Docker build context path'
        type: string
        default: '.'
      dockerfile:
        description: 'Path to Dockerfile'
        type: string
        default: 'Dockerfile'
      platforms:
        description: 'Platforms to build for (comma-separated)'
        type: string
        default: 'linux/amd64'

      # GitHub Container Registry
      github-enable:
        description: 'Push to GitHub Container Registry'
        type: boolean
        default: true
      github-package-name:
        description: 'GitHub Container Registry package name. Defaults to GitHub repository name'
        type: string
        default: ''

      # Google Artifact Registry
      google-enable:
        description: 'Push to Google Artifact Registry'
        type: boolean
        default: false
      google-workload-identity-provider:
        description: 'Google Cloud workload identity provider. Required, if google-enable is true'
        type: string
        default: ''
      google-service-account:
        description: 'Google Cloud service account email. Required, if google-enable is true'
        type: string
        default: ''
      google-project:
        description: 'Google Cloud project ID. Required, if google-enable is true'
        type: string
        default: ''
      google-registry-location:
        description: 'Google Artifact Registry location. Required, if google-enable is true'
        type: string
        default: ''
      google-repository:
        description: 'Google Artifact Registry repository path. Required, if google-enable is true'
        type: string
        default: ''
      google-package-name:
        description: 'Google Artifact Registry package name. Defaults to GitHub repository name'
        type: string
        default: ''

      # Amazon Elastic Container Registry
      amazon-enable:
        description: 'Push to Amazon ECR'
        type: boolean
        default: false
      amazon-aws-region:
        description: 'Amazon AWS region. Required, if amazon-enable is true'
        type: string
        default: ''
      amazon-aws-account-id:
        description: 'Amazon AWS account ID. Required, if amazon-enable is true'
        type: string
        default: ''
      amazon-role-to-assume:
        description: 'Amazon AWS IAM role to assume. Required, if amazon-enable is true'
        type: string
        default: ''
      amazon-package-name:
        description: 'Amazon ECR package name. Defaults to GitHub repository name'
        type: string
        default: ''

jobs:
  build-push:
    name: 'Docker Build and Push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: 'GitHub Container Registry: Setup'
        id: github
        run: |
          if [ "${{ inputs.github-enable }}" != "true" ]
          then
            echo "enabled=false" | tee -a "$GITHUB_OUTPUT"
          else
            missing_inputs=''
            missing_secrets=''

            [ -n "${{ secrets.GITHUB_TOKEN }}" ] || missing_secrets="$missing_secrets GITHUB_TOKEN"

            if [ -n "$missing_inputs$missing_secrets" ]
            then
              echo "::error::Missing required inputs ($missing_inputs) or secrets ($missing_secrets)." >&2
              exit 64 # EX_USAGE
            fi

            # ghcr.io/:ORGANISATION/:IMAGE_NAME

            registry="ghcr.io/${{ github.repository_owner }}"
            echo "registry=$registry" | tee -a "$GITHUB_OUTPUT"

            package_name="${{ inputs.github-package-name }}"
            if [ -z "$package_name" ]
            then
              package_name="${{ github.event.repository.name }}"
            fi
            echo "package_name=$package_name" | tee -a "$GITHUB_OUTPUT"

            echo "enabled=true" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: 'GitHub Container Registry: Authenticate'
        if: steps.github.outputs.enabled == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Google Artifact Registry: Setup'
        id: google
        run: |
          if [ "${{ inputs.google-enable }}" != "true" ]
          then
            echo "enabled=false" | tee -a "$GITHUB_OUTPUT"
          else
            missing_inputs=''
            missing_secrets=''

            [ -n "${{ inputs.google-project }}" ] || missing_inputs="$missing_inputs google-project"
            [ -n "${{ inputs.google-registry-location }}" ] || missing_inputs="$missing_inputs google-registry-location"
            [ -n "${{ inputs.google-repository }}" ]|| missing_inputs="$missing_inputs google-repository"

            [ -n "${{ inputs.google-workload-identity-provider }}" ] || missing_inputs="$missing_inputs google-workload-identity-provider"
            [ -n "${{ inputs.google-service-account }}" ] || missing_inputs="$missing_inputs google-service-account"

            if [ -n "$missing_inputs$missing_secrets" ]
            then
              echo "::error::Missing required inputs ($missing_inputs) or secrets ($missing_secrets)." >&2
              exit 64 # EX_USAGE
            fi

            # :LOCATION-docker.pkg.dev/:PROJECT/:REPOSITORY/:IMAGE_NAME

            registry="${{ inputs.google-registry-location }}-docker.pkg.dev/${{ inputs.google-project }}/${{ inputs.google-repository }}"
            echo "registry=$registry" | tee -a "$GITHUB_OUTPUT"

            package_name="${{ inputs.google-package-name }}"
            if [ -z "$package_name" ]
            then
              package_name="${{ github.event.repository.name }}"
            fi
            echo "package_name=$package_name" | tee -a "$GITHUB_OUTPUT"

            echo "enabled=true" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: 'Google Artifact Registry: Authenticate to Google Cloud'
        if: steps.google.outputs.enabled == 'true'
        id: google_auth
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          project_id: ${{ inputs.google-project }}
          workload_identity_provider: ${{ inputs.google-workload-identity-provider }}
          service_account: ${{ inputs.google-service-account }}

      - name: 'Google Artifact Registry: Authenticate to Google Artifact Registry'
        if: steps.google.outputs.enabled == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.google.outputs.registry }}
          username: oauth2accesstoken
          password: ${{ steps.google_auth.outputs.access_token }}

      - name: 'Amazon Elastic Container Registry: Setup'
        id: amazon
        run: |
          if [ "${{ inputs.amazon-enable }}" != "true" ]
          then
            echo "enabled=false" | tee -a "$GITHUB_OUTPUT"
          else
            missing_inputs=''
            missing_secrets=''

            [ -n "${{ inputs.amazon-aws-account-id }}" ] || missing_inputs="$missing_inputs amazon-aws-account-id"
            [ -n "${{ inputs.amazon-aws-region }}" ] || missing_inputs="$missing_inputs amazon-aws-region"
            [ -n "${{ inputs.amazon-role-to-assume }}" ] || missing_inputs="$missing_inputs amazon-role-to-assume"

            if [ -n "$missing_inputs$missing_secrets" ]
            then
              echo "::error::Missing required inputs ($missing_inputs) or secrets ($missing_secrets)." >&2
              exit 64 # EX_USAGE
            fi

            # :AWS_ACCOUNT_ID.dkr.ecr.:REGION.amazonaws.com/:IMAGE_NAME

            registry="${{ inputs.amazon-aws-account-id }}.dkr.ecr.${{ inputs.amazon-aws-region }}.amazonaws.com"
            echo "registry=$registry" | tee -a "$GITHUB_OUTPUT"

            package_name="${{ inputs.amazon-package-name }}"
            if [ -z "$package_name" ]
            then
              package_name="${{ github.event.repository.name }}"
            fi
            echo "package_name=$package_name" | tee -a "$GITHUB_OUTPUT"

            echo "enabled=true" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: 'Amazon Elastic Container Registry: Configure AWS credentials'
        if: steps.amazon.outputs.enabled == 'true'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ inputs.amazon-aws-region }}
          role-to-assume: ${{ inputs.amazon-role-to-assume }}

      - name: 'Amazon Elastic Container Registry: Authenticate to Amazon Elastic Container Registry'
        if: steps.amazon.outputs.enabled == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.amazon.outputs.registry }}

      - name: 'Verify setup'
        run: |
          if [ "${{ steps.github.outputs.enabled }}" != "true" ] && \
             [ "${{ steps.google.outputs.enabled }}" != "true" ] && \
             [ "${{ steps.amazon.outputs.enabled }}" != "true" ]
          then
            echo "::error::No container registry is enabled for pushing." >&2
            exit 64 # EX_USAGE
          fi

      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Determine tags to use'
        id: tags
        run: |
          # Always include `git-<SHORT_SHA>`
          TAGS="git-$( git rev-parse --short HEAD )"

          # Note: This is a glob, not a regular rexpression, so [0-9]*
          # acts as /[0-9].*/ in regex. This might match more than
          # intended, but it’s a trade–off not to complicate things.
          version_glob="v[0-9]*.[0-9]*.[0-9]*"

          VERSION_TAG="$(
            git describe --tags --abbrev=0 --exact --match="$version_glob" 2>/dev/null
          )"

          if [ -z "$VERSION_TAG" ]
          then
            # Use “edge” if not building a tagged version
            TAGS="$TAGS edge"
          else
            TAGS="$TAGS ${VERSION_TAG}"
            if ! echo "$VERSION_TAG" | grep -q '-'
            then
              TAGS="$TAGS $( echo "${VERSION_TAG}" | grep -oE '^v[0-9]+' )"
              TAGS="$TAGS $( echo "${VERSION_TAG}" | grep -oE '^v[0-9]+\.[0-9]+' )"
              # Use “latest” if tagging a non–prerelease version
              TAGS="$TAGS latest"
            fi
          fi

          TAGS="$( echo "$TAGS" | tr ' ' '\n' )"

          {
            echo "Tagging image with:"
            echo
            # shellcheck disable=SC2001,SC2016
            echo "$TAGS" | sed 's/.*/- `&`/'
            echo
          } >> "$GITHUB_STEP_SUMMARY"

          URLS="$(
            # GitHub Container Registry
            if [ "${{ steps.github.outputs.enabled }}" == "true" ]
            then
              echo "${{ steps.github.outputs.registry }}/${{ steps.github.outputs.package_name }}"
            fi

            # Google Artifact Registry
            if [ "${{ steps.google.outputs.enabled }}" == "true" ]
            then
              echo "${{ steps.google.outputs.registry }}/${{ steps.google.outputs.package_name }}"
            fi

            # Amazon ECR
            if [ "${{ steps.amazon.outputs.enabled }}" == "true" ]
            then
              echo "${{ steps.amazon.outputs.registry }}/${{ steps.amazon.outputs.package_name }}"
            fi
          )"

          {
            echo "Pushing to:"
            echo
            # shellcheck disable=SC2001
            echo "$URLS" | sed 's|^|- https://|'
            echo
          } >> "$GITHUB_STEP_SUMMARY"

          {
            echo "tags<<EOF"
            for tag in $TAGS
            do
              for url in $URLS
              do
                if [ -n "$url" ]
                then
                  echo "${url}:${tag}"
                fi
              done
            done
            echo "EOF"
          } | tee -a "$GITHUB_OUTPUT"

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      # Build and Push as separate steps, so we can see durations

      - name: 'Build'
        uses: docker/build-push-action@v6
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          provenance: true
          tags: |
            ${{ steps.tags.outputs.tags }}
          build-args: |
            ${{ secrets.BUILD_ARGS }}

      - name: 'Push'
        if: inputs.dry-run == false
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          provenance: true
          tags: |
            ${{ steps.tags.outputs.tags }}
          build-args: |
            ${{ secrets.BUILD_ARGS }}
