name: 'Docker Build and Push: Setup Google Artifact Registry'
on:
  workflow_call:
    inputs:
      project:
        description: >
          Google Cloud project ID.
        type: string
        required: true
      registry-location:
        description: >
          Registry location.
        type: string
        required: true
      repository:
        description: >
          Repository name.
        type: string
        required: true
      workload-identity-provider:
        description: >
          Workload Identity Provider.
        type: string
        required: true
      service-account:
        description: >
          Service Account email.
        type: string
        required: true
      image-name:
        description: >
          Image name.
          Leave empty to use repository name.
        type: string
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.setup.outputs.registry }}
      image-name: ${{ steps.setup.outputs.image-name }}
      url: ${{ steps.setup.outputs.url }}
    steps:
      - name: 'Validate inputs'
        id: setup
        run: |
          registry="${{ inputs.registry-location }}-docker.pkg.dev/${{ inputs.project }}/${{ inputs.repository }}"
          echo "registry=$registry" | tee -a "$GITHUB_OUTPUT"

          image_name="${{ inputs.image-name }}"
          if [ -z "$image_name" ]
          then
            image_name="${{ github.event.repository.name }}"
          fi
          echo "image-name=$image_name" | tee -a "$GITHUB_OUTPUT"

          echo "enabled=true" | tee -a "$GITHUB_OUTPUT"

          echo "url=${registry}/$image_name" | tee -a "$GITHUB_OUTPUT"

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: github-actions/auth@v3
        with:
          token_format: access_token
          project_id: ${{ inputs.project }}
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.service-account }}

      - name: 'Authenticate to Google Artifact Registry'
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.setup.outputs.registry }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
