# Docker Build and Push
#
# Template to use with this workflow:
# https://github.com/verkstedt/.github/tree/main/workflow-templates/docker-build-push.yaml
#
# Build and push Docker images to multiple registries:
# - GitHub Container Registry (GHCR)
# - Google Artifact Registry
# - Amazon ECR (AWS Elastic Container Registry)
#
# Will tag all images with:
# - sha of the commit (`git-<short_sha>`)
# - then depending if version change is detected:
#   - NO (meant for preview deployment)
#     - `edge`
#   - YES (meant for production deployment, unless it’s prerelease)
#     - tag with `v<new_version>`
#     - if version is not prerelease also with:
#       - `latest`
#       - `v<major>` and `v<major>.<minor>`
#
# # GitHub actions variables
#
# Best to set these on organisation level. If you push to different
# repositories in different repos, set everything in org and change only
# `DOCKER_…_ENABLE` in repos.
#
# ## GitHub Container Registry
#
# - `DOCKER_GITHUB_ENABLE=true`
# - if you don’t want to use repo name as package name, also set
#   `DOCKER_GITHUB_PACKAGE_NAME`
#
# ##  Google Artifact Registry
#
# - `DOCKER_GOOGLE_ENABLE=true`
# - `DOCKER_GOOGLE_WORKLOAD_IDENTITY_PROVIDER`
# - `DOCKER_GOOGLE_SERVICE_ACCOUNT`
# - `DOCKER_GOOGLE_PROJECT`
# - `DOCKER_GOOGLE_REGISTRY_LOCATION`
# - `DOCKER_GOOGLE_REPOSITORY`
# - if you don’t want to use repo name as package name, also set
#   `DOCKER_GOOGLE_PACKAGE_NAME`
#
# Depending on your setup, you might also need to run a command like
# this (replace `$…` with your values):
#
# ```sh
# gcloud iam service-accounts add-iam-policy-binding \
#   "$GOOGLE_SERVICE_ACCOUNT" \
#   --project="$GOOGLE_PROJECT_NAME" \
#   --role=roles/iam.workloadIdentityUser \
#   --member="principalSet://iam.googleapis.com/projects/$PROJECT_ID/locations/global/workloadIdentityPools/github/attribute.repository/$REPO_ORG/$REPO_NAME"
# ```
#
# ## Amazon ECR
#
# - `DOCKER_AMAZON_ENABLE=true`
# - `DOCKER_AMAZON_AWS_REGION`
# - `DOCKER_AMAZON_AWS_ACCOUNT_ID`
# - `DOCKER_AMAZON_ROLE_TO_ASSUME`
# - if you don’t want to use repo name as package name, also set
#   `DOCKER_AMAZON_PACKAGE_NAME`

name: Docker Build and Push
on:
  workflow_call:
    secrets:
      BUILD_ARGS:
        description: 'Build arguments for Docker build (multiline string)'
      SLACK_BOT_TOKEN:
        description: 'Slack bot token, to notify a Slack channel of successful deployment'
        required: true

    inputs:
      dry-run:
        description: 'Dry run mode (no pushing to registries)'
        type: boolean
        default: false
      # Build configuration
      platforms:
        description: 'Platforms to build for (comma-separated)'
        type: string
        default: 'linux/amd64'

jobs:
  build-push:
    name: 'Docker Build and Push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'GitHub Container Registry: Setup'
        id: github
        run: |
          if [ "${{ vars.DOCKER_GITHUB_ENABLE }}" != "true" ]
          then
            echo "enabled=false" | tee -a "$GITHUB_OUTPUT"
          else
            missing_vars=''
            missing_secrets=''

            [ -n "${{ secrets.GITHUB_TOKEN }}" ] || missing_secrets="$missing_secrets GITHUB_TOKEN"

            if [ -n "$missing_vars$missing_secrets" ]
            then
              echo "::error::Missing required vars ($missing_vars) or secrets ($missing_secrets)." >&2
              exit 64 # EX_USAGE
            fi

            # ghcr.io/:ORGANISATION/:IMAGE_NAME

            registry="ghcr.io/${{ github.repository_owner }}"
            echo "registry=$registry" | tee -a "$GITHUB_OUTPUT"

            package_name="${{ vars.DOCKER_GITHUB_PACKAGE_NAME }}"
            if [ -z "$package_name" ]
            then
              package_name="${{ github.event.repository.name }}"
            fi
            echo "package_name=$package_name" | tee -a "$GITHUB_OUTPUT"

            echo "enabled=true" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: 'GitHub Container Registry: Authenticate'
        if: steps.github.outputs.enabled == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Google Artifact Registry: Setup'
        id: google
        run: |
          if [ "${{ vars.DOCKER_GOOGLE_ENABLE }}" != "true" ]
          then
            echo "enabled=false" | tee -a "$GITHUB_OUTPUT"
          else
            missing_vars=''
            missing_secrets=''

            [ -n "${{ vars.DOCKER_GOOGLE_PROJECT }}" ] || missing_vars="$missing_vars DOCKER_GOOGLE_PROJECT"
            [ -n "${{ vars.DOCKER_GOOGLE_REGISTRY_LOCATION }}" ] || missing_vars="$missing_vars DOCKER_GOOGLE_REGISTRY_LOCATION"
            [ -n "${{ vars.DOCKER_GOOGLE_REPOSITORY }}" ]|| missing_vars="$missing_vars DOCKER_GOOGLE_REPOSITORY"

            [ -n "${{ vars.DOCKER_GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}" ] || missing_vars="$missing_vars DOCKER_GOOGLE_WORKLOAD_IDENTITY_PROVIDER"
            [ -n "${{ vars.DOCKER_GOOGLE_SERVICE_ACCOUNT }}" ] || missing_vars="$missing_vars DOCKER_GOOGLE_SERVICE_ACCOUNT"

            if [ -n "$missing_vars$missing_secrets" ]
            then
              echo "::error::Missing required vars ($missing_vars) or secrets ($missing_secrets)." >&2
              exit 64 # EX_USAGE
            fi

            # :LOCATION-docker.pkg.dev/:PROJECT/:REPOSITORY/:IMAGE_NAME

            registry="${{ vars.DOCKER_GOOGLE_REGISTRY_LOCATION }}_docker.pkg.dev/${{ vars.DOCKER_GOOGLE_PROJECT }}/${{ vars.DOCKER_GOOGLE_REPOSITORY }}"
            echo "registry=$registry" | tee -a "$GITHUB_OUTPUT"

            package_name="${{ vars.DOCKER_GOOGLE_PACKAGE_NAME }}"
            if [ -z "$package_name" ]
            then
              package_name="${{ github.event.repository.name }}"
            fi
            echo "package_name=$package_name" | tee -a "$GITHUB_OUTPUT"

            echo "enabled=true" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: 'Google Artifact Registry: Authenticate to Google Cloud'
        if: steps.google.outputs.enabled == 'true'
        id: google_auth
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          project_id: ${{ vars.DOCKER_GOOGLE_PROJECT }}
          workload_identity_provider: ${{ vars.DOCKER_GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.DOCKER_GOOGLE_SERVICE_ACCOUNT }}

      - name: 'Google Artifact Registry: Authenticate to Google Artifact Registry'
        if: steps.google.outputs.enabled == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.google.outputs.registry }}
          username: oauth2accesstoken
          password: ${{ steps.google_auth.outputs.access_token }}

      - name: 'Amazon Elastic Container Registry: Setup'
        id: amazon
        run: |
          if [ "${{ vars.DOCKER_AMAZON_ENABLE }}" != "true" ]
          then
            echo "enabled=false" | tee -a "$GITHUB_OUTPUT"
          else
            missing_vars=''
            missing_secrets=''

            [ -n "${{ vars.DOCKER_AMAZON_AWS_ACCOUNT_ID }}" ] || missing_vars="$missing_vars DOCKER_AMAZON_AWS_ACCOUNT_ID"
            [ -n "${{ vars.DOCKER_AMAZON_AWS_REGION }}" ] || missing_vars="$missing_vars DOCKER_AMAZON_AWS_REGION"
            [ -n "${{ vars.DOCKER_AMAZON_ROLE_TO_ASSUME }}" ] || missing_vars="$missing_vars DOCKER_AMAZON_ROLE_TO_ASSUME"

            if [ -n "$missing_vars$missing_secrets" ]
            then
              echo "::error::Missing required vars ($missing_vars) or secrets ($missing_secrets)." >&2
              exit 64 # EX_USAGE
            fi

            # :AWS_ACCOUNT_ID.dkr.ecr.:REGION.amazonaws.com/:IMAGE_NAME

            registry="${{ vars.DOCKER_AMAZON_AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.DOCKER_AMAZON_AWS_REGION }}.amazonaws.com"
            echo "registry=$registry" | tee -a "$GITHUB_OUTPUT"

            package_name="${{ vars.DOCKER_AMAZON_PACKAGE_NAME }}"
            if [ -z "$package_name" ]
            then
              package_name="${{ github.event.repository.name }}"
            fi
            echo "package_name=$package_name" | tee -a "$GITHUB_OUTPUT"

            echo "enabled=true" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: 'Amazon Elastic Container Registry: Configure AWS credentials'
        if: steps.amazon.outputs.enabled == 'true'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws_region: ${{ vars.DOCKER_AMAZON_AWS_REGION }}
          role_to_assume: ${{ vars.DOCKER_AMAZON_ROLE_TO_ASSUME }}

      - name: 'Amazon Elastic Container Registry: Authenticate to Amazon Elastic Container Registry'
        if: steps.amazon.outputs.enabled == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.amazon.outputs.registry }}

      - name: 'Verify setup'
        run: |
          if [ "${{ steps.github.outputs.enabled }}" != "true" ] && \
             [ "${{ steps.google.outputs.enabled }}" != "true" ] && \
             [ "${{ steps.amazon.outputs.enabled }}" != "true" ]
          then
            echo "::error::No container registry is enabled for pushing." >&2
            exit 64 # EX_USAGE
          fi

      - name: 'Determine tags to use'
        id: tags
        run: |
          # Always include `git-<SHORT_SHA>`
          TAGS="git-$( git rev-parse --short HEAD )"

          # Note: This is a glob, not a regular rexpression, so [0-9]*
          # acts as /[0-9].*/ in regex. This might match more than
          # intended, but it’s a trade–off not to complicate things.
          version_glob="v[0-9]*.[0-9]*.[0-9]*"

          VERSION_TAG="$(
            git describe --tags --abbrev=0 --exact --match="$version_glob" 2>/dev/null || :
          )"

          if [ -z "$VERSION_TAG" ]
          then
            # Use “edge” if not building a tagged version
            TAGS="$TAGS edge"
          else
            TAGS="$TAGS ${VERSION_TAG}"
            if ! echo "$VERSION_TAG" | grep -q '-'
            then
              TAGS="$TAGS $( echo "${VERSION_TAG}" | grep -oE '^v[0-9]+\.[0-9]+' )"
              TAGS="$TAGS $( echo "${VERSION_TAG}" | grep -oE '^v[0-9]+' )"
              # Use “latest” if tagging a non–prerelease version
              TAGS="$TAGS latest"
            fi
          fi

          TAGS="$( echo "$TAGS" | tr ' ' '\n' )"

          {
            echo "Tagging image with:"
            echo
            # shellcheck disable=SC2001,SC2016
            echo "$TAGS" | sed 's/.*/- `&`/'
            echo
          } >> "$GITHUB_STEP_SUMMARY"

          URLS="$(
            # GitHub Container Registry
            if [ "${{ steps.github.outputs.enabled }}" == "true" ]
            then
              echo "${{ steps.github.outputs.registry }}/${{ steps.github.outputs.package_name }}"
            fi

            # Google Artifact Registry
            if [ "${{ steps.google.outputs.enabled }}" == "true" ]
            then
              echo "${{ steps.google.outputs.registry }}/${{ steps.google.outputs.package_name }}"
            fi

            # Amazon ECR
            if [ "${{ steps.amazon.outputs.enabled }}" == "true" ]
            then
              echo "${{ steps.amazon.outputs.registry }}/${{ steps.amazon.outputs.package_name }}"
            fi
          )"

          {
            echo "Pushing to:"
            echo
            # shellcheck disable=SC2001
            echo "$URLS" | sed 's|^|- https://|'
            echo
          } >> "$GITHUB_STEP_SUMMARY"

          {
            echo "tags<<EOF"
            for tag in $TAGS
            do
              for url in $URLS
              do
                if [ -n "$url" ]
                then
                  echo "${url}:${tag}"
                fi
              done
            done
            echo "EOF"
          } | tee -a "$GITHUB_OUTPUT"

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      # Build and Push as separate steps, so we can see durations

      - name: 'Build and Push'
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.dry-run != true }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ vars.DOCKER_CONTEXT }}
          file: ${{ vars.DOCKER_DOCKERFILE }}
          platforms: ${{ inputs.platforms }}
          provenance: true
          tags: |
            ${{ steps.tags.outputs.tags }}
          build-args: |
            ${{ secrets.BUILD_ARGS }}

      - name: Notify
        if: inputs.dry-run != true
        uses: verkstedt/actions/notify-status@v1
        with:
          status: success
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ vars.SLACK_CHANNEL_ID }}
