name: 'Notify about failure on main branch'

# This MUST be specified as a job that `needs` all of the other jobs in
# the workflow:
#
# notify-main-branch-failure:
#   name: Notify about failure on main branch
#   needs:
#     - setup
#     - …
#   if: always() && github.ref_name == github.event.repository.default_branch
#   uses: verkstedt/actions/.github/workflows/notify-main-branch-failure.yaml@v1
#   with:
#     status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
#   permissions:
#     actions: read
#   secrets: inherit

on:
  workflow_call:
    inputs:
      status:
        description: >
          Result of the calling workflow’s jobs. One of: success, failure.
          Not passing it is deprecated and treated as failure.
        type: string
        required: false
        default: ''

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  notify-main-branch-failure:
    name: Notify about failure on main branch
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Verify workflow setup
        shell: sh
        env:
          STATUS: ${{ inputs.status }}
        run: |
          exit_code=0

          if [ -z "${{ secrets.SLACK_BOT_TOKEN }}" ]
          then
            # shellcheck disable=SC1111
            echo "::error::Missing secret SLACK_BOT_TOKEN. Go to https://api.slack.com/apps/, create a bot, go to “OAuth & Permissions”. Add chat:write permission and grab a token."
            exit_code=78
          fi

          if [ -z "${{ vars.SLACK_CHANNEL_ID }}" ]
          then
            echo "::error::Missing var SLACK_CHANNEL_ID. This is _not_ a channel name. You can grab the ID from page URL."
            exit_code=78
          fi

          case "$STATUS" in
            success|failure)
              ;;
            '')
              # shellcheck disable=SC1111
              echo "::warning::Not passing “status” input is deprecated and will become an error. See usage in https://github.com/verkstedt/actions/blob/v1/.github/workflows/notify-main-branch-failure.yaml"
              ;;
            *)
              # shellcheck disable=SC1111
              echo "::error::Invalid status input “$STATUS”. Expected success or failure."
              exit_code=78
              ;;
          esac

          exit $exit_code

      - name: Notify about failure on main branch
        if: inputs.status != 'success'
        uses: verkstedt/actions/notify-status@v1
        with:
          status: failure
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ vars.SLACK_CHANNEL_ID }}

      - name: Notify about main branch being back to normal
        if: inputs.status == 'success'
        uses: verkstedt/actions/notify-status@v1
        with:
          status: success
          text: Back to normal after previous failure.
          only-after-failure: true
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ vars.SLACK_CHANNEL_ID }}
